name: mailman 

on:
  push:
    paths:
      - 'mailman/**'


jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-golang@v3
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          go test -v ./...



