name: mailman-ci

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - 'mailman/**'


jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          cd mailman/
          go test -v ./...
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./mailman/Dockerfile
          push: true
          tags: omerbd/mailman:${{ steps.version.outputs.version }}


