name: storyteller-ci

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - 'storyteller/**'


jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r storyteller/requirements.txt
      - name: Run tests
        env:
          EDENAI_TOKEN: ${{ secrets.EDENAI_TOKEN }}
          EDENAI_PROVIDER: ${{ env.EDENAI_PROVIDER }}
          EDENAI_URL: ${{ env.EDENAI_URL }}
        run: |
          cd storyteller
          python -m unittest discover app/tests
      - name: Log in to the Container registry
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version
        with:
          scheme: semver
          increment: patch
      - name: Build and push Docker image
        uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
        with:
          context: .
          file: ./storyteller/Dockerfile
          build-args: |
            EDENAI_URL=${{ env.EDENAI_URL }}
            EDENAI_PROVIDER=${{ env.EDENAI_PROVIDER }}
            STORYTELLER_PROVIDER=${{ env.STORYTELLER_PROVIDER }}
          push: true
          tags: omerbd/storyteller:${{ steps.version.outputs.version }}



