name: storyteller 

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
    paths:
      - 'storyteller/**'


jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v2
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r storyteller/requirements.txt
      - name: Run tests
        env:
          EDENAI_TOKEN: ${{ secrets.EDENAI_TOKEN }}
        run: |
          cd storyteller
          python -m unittest discover app/tests



